project_id = "oztpfiuahuzehwtvspfz"

[functions.generate-trip]
verify_jwt = false

[functions.generate-hero-image]
verify_jwt = false

[functions.suggest-alternatives]
verify_jwt = false

[functions.search-places]
verify_jwt = false

[functions.search-flights]
verify_jwt = false

[functions.search-hotels]
verify_jwt = false

[functions.suggest-flights]
verify_jwt = false
